name = "ttdm-review"
compatibility_date = "2024-12-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "ttdm-review"
database_id = "9bb3e316-4b90-4b12-b361-99b8e56d5071"

